#!/usr/bin/env python3
"""
05_lightrag/setup.py
One-time setup script for LightRAG + Ollama on the school computer.

Checks:
  - Python packages (lightrag-hku, etc.)
  - Ollama is running and the configured model is available
  - Writes lightrag_config.yaml

Usage:
    python pipeline/05_lightrag/setup.py
    python pipeline/05_lightrag/setup.py --model qwen3.5:35b
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

REQUIRED_PACKAGES = [
    "lightrag",       # lightrag-hku installs as 'lightrag'
    "openpyxl",
    "pandas",
    "tqdm",
]

DEFAULT_CONFIG = {
    "working_dir": "output/lightrag_storage",
    # MoE model: 80B total params, ~3B active per token — fast inference,
    # high knowledge capacity, fits in 128GB unified memory.
    # Always use an *Instruct* variant — base models won't reliably output JSON.
    "llm_model": "qwen3.5:35b",
    "embedding_model": "nomic-embed-text",
    "ollama_base_url": os.environ.get("OLLAMA_URL",
                           f"http://{os.environ['OLLAMA_HOST']}" if "OLLAMA_HOST" in os.environ
                           else "http://localhost:11434"),
    "chunk_size": 1200,
    "chunk_overlap": 100,
    "max_async": 4,
    "max_tokens": 32768,
}

CONFIG_TEMPLATE = """\
# LightRAG configuration for emgraphrag
# Generated by pipeline/05_lightrag/setup.py

# Storage directory (LightRAG graph + vector index — built-in file-based storage)
working_dir: {working_dir}

# LLM settings (Ollama)
llm_model: {llm_model}
ollama_base_url: {ollama_base_url}
max_tokens: {max_tokens}

# Embedding model (Ollama)
embedding_model: {embedding_model}

# Chunking
chunk_size: {chunk_size}
chunk_overlap: {chunk_overlap}

# Concurrency (tune for your GPU / RAM)
max_async: {max_async}
"""


def check_packages():
    print("Checking Python packages...")
    missing = []
    for pkg in REQUIRED_PACKAGES:
        try:
            __import__(pkg)
            print(f"  OK  {pkg}")
        except ImportError:
            print(f"  MISSING  {pkg}")
            missing.append(pkg)

    if missing:
        print(f"\nInstalling missing packages: {', '.join(missing)}")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install"] + missing
        )
        print("Packages installed.")
    else:
        print("All packages present.")


def check_ollama(base_url: str, model: str, embed_model: str) -> bool:
    print(f"\nChecking Ollama at {base_url}...")
    try:
        import urllib.request
        import json as _json

        req = urllib.request.urlopen(f"{base_url}/api/tags", timeout=5)
        data = _json.loads(req.read())
        available = {m["name"] for m in data.get("models", [])}
        print(f"  Ollama: OK ({len(available)} models available)")

        if model in available or any(m.startswith(model.split(":")[0]) for m in available):
            print(f"  LLM model '{model}': found")
        else:
            print(f"  LLM model '{model}': NOT FOUND")
            print(f"    Pull with: ollama pull {model}")

        if embed_model in available or any(m.startswith(embed_model.split(":")[0]) for m in available):
            print(f"  Embedding model '{embed_model}': found")
        else:
            print(f"  Embedding model '{embed_model}': NOT FOUND")
            print(f"    Pull with: ollama pull {embed_model}")

        return True
    except Exception as e:
        print(f"  Ollama: FAILED — {e}")
        print("  Start Ollama with: sudo systemctl start ollama")
        print(f"  Then pull models: ollama pull {model} && ollama pull {embed_model}")
        return False


def write_config(config: dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(CONFIG_TEMPLATE.format(**config), encoding="utf-8")
    print(f"\nConfig written: {path}")


def main():
    parser = argparse.ArgumentParser(description="Set up LightRAG for emgraphrag.")
    parser.add_argument("--model", default=DEFAULT_CONFIG["llm_model"],
                        help=f"Ollama LLM model (default: {DEFAULT_CONFIG['llm_model']})")
    parser.add_argument("--embed-model", default=DEFAULT_CONFIG["embedding_model"],
                        help=f"Ollama embedding model (default: {DEFAULT_CONFIG['embedding_model']})")
    parser.add_argument("--ollama-url", default=DEFAULT_CONFIG["ollama_base_url"])
    parser.add_argument("--working-dir", default=DEFAULT_CONFIG["working_dir"])
    parser.add_argument("--config-out", default="lightrag_config.yaml")
    args = parser.parse_args()

    print("=" * 50)
    print("emgraphrag LightRAG Setup")
    print("=" * 50)

    check_packages()

    config = {**DEFAULT_CONFIG}
    config["llm_model"] = args.model
    config["embedding_model"] = args.embed_model
    config["ollama_base_url"] = args.ollama_url
    config["working_dir"] = args.working_dir

    ollama_ok = check_ollama(config["ollama_base_url"], config["llm_model"], config["embedding_model"])

    write_config(config, Path(args.config_out))

    print("\n" + "=" * 50)
    if ollama_ok:
        print("Setup complete! All checks passed.")
        print("Next steps:")
        print("  1. python pipeline/05_lightrag/ingest.py --limit 50  # test first")
        print("  2. python pipeline/05_lightrag/ingest.py              # full run")
        print("  3. python pipeline/05_lightrag/query.py 'Your question here'")
    else:
        print("Setup incomplete — resolve the issues above, then re-run.")
    print("=" * 50)


if __name__ == "__main__":
    main()
